name: Continous Integration

on:
  pull_request:
    branches: ['**']
  push:
    branches: ['**']
    tags: [v*]

jobs:
  build:
    name: Build and Test
    runs-on: windows-2019
    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build Docker images
        run: |
          docker build windows/nanoserver-1809

