name: Continous Integration

on:
  pull_request:
    branches: ['**']
  push:
    branches: ['**']
    tags: [v*]

jobs:
  build:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 2
      matrix:
        os: [windows-2019, windows-2022]
        include:
        - os: windows-2019
          dockerfile: windows/nanoserver-1809/Dockerfile
          context: windows
        - os: windows-2022
          dockerfile: windows/nanoserver-ltsc2022/Dockerfile
          context: windows
    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build Docker images
        run: |
          docker build -f ${{ matrix.dockerfile }} ${{ matrix.context }}

